import { useMemo, useState } from 'react'
import { mockAnnouncements, mockParticipant, mockPayments, mockProgramme } from '../../data/mockPlatform'
import { DataTable, tableCellClass, tableHeadClass } from '../../components/platform/DataTable'
import { PageHeader } from '../../components/platform/PageHeader'
import { StatusBadge } from '../../components/platform/StatusBadge'

function Panel({ title, children }: React.PropsWithChildren<{ title: string }>) { return <section className="border border-slate-200 bg-white p-5 sm:p-6"><h2 className="font-display text-2xl font-semibold text-mkaps-navy">{title}</h2><div className="mt-5">{children}</div></section> }
function Details({ rows }: { rows: Array<[string, string]> }) { return <dl className="grid gap-5 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label}><dt className="text-[.62rem] font-bold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value}</dd></div>)}</dl> }
function Shell({ title, eyebrow, children }: React.PropsWithChildren<{ title: string; eyebrow: string }>) { return <div className="mx-auto max-w-6xl"><PageHeader title={title} eyebrow={eyebrow} />{children}</div> }

export function MyRegistrationPage() { return <Shell eyebrow="Participant record" title="My Registration"><div className="mt-7 grid gap-5 lg:grid-cols-2"><Panel title="Registration"><Details rows={[["Registration number",mockParticipant.registrationNumber],["Status","Confirmed"],["Participant",mockParticipant.name],["Country",mockParticipant.country],["Church / Ministry","Grace Fellowship Moshi"],["Payment preference","Mobile Money"]]} /></Panel><Panel title="Summit Arrangements"><Details rows={[["Accommodation",mockParticipant.accommodation],["Transport",mockParticipant.transport],["Kilimanjaro",mockParticipant.kilimanjaroActivity],["Emergency contact","Daniel Mwakalinga · +255 700 000 241"]]} /></Panel></div><button type="button" onClick={() => window.alert('Prototype only: editing will not be persisted.')} className="button-navy mt-6 inline-flex">Edit details</button></Shell> }

export function PassPage() { const cells = useMemo(() => Array.from({ length: 121 }, (_, index) => ((index * 7 + Math.floor(index / 11) * 3) % 5) < 2), []); return <Shell eyebrow="Digital credential" title="My QR Pass"><div className="mt-8 max-w-3xl overflow-hidden border border-mkaps-gold/40 bg-mkaps-navy p-7 text-white shadow-xl sm:p-10"><div className="flex flex-col gap-8 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold tracking-[.2em] text-mkaps-gold">MKAPS 2027</p><h2 className="mt-5 font-display text-4xl font-semibold">{mockParticipant.name}</h2><p className="mt-3 text-sm text-white/65">{mockParticipant.registrationNumber}</p><dl className="mt-7 space-y-3 text-sm"><div><dt className="text-white/45">Country</dt><dd>{mockParticipant.country}</dd></div><div><dt className="text-white/45">Badge type</dt><dd>General Participant</dd></div></dl><div className="mt-6"><StatusBadge status="confirmed" /></div></div><div className="shrink-0 bg-white p-3"><div aria-label="Mock QR code, frontend only" className="grid size-44 grid-cols-11">{cells.map((active,index) => <span key={index} className={active ? 'bg-mkaps-navy' : 'bg-white'} />)}</div></div></div><p className="mt-7 border-t border-white/15 pt-5 text-[.62rem] uppercase tracking-wider text-white/45">Mock visual only · contains no encoded personal data</p></div><button type="button" onClick={() => window.print()} className="button-navy mt-6 inline-flex">Download pass / Print</button></Shell> }

export function ProgrammePage() { const [tab,setTab]=useState('Today'); const [filter,setFilter]=useState('All'); const categories=['All','Prayer','Worship','Teaching','Leadership','Fellowship','Mountain Activity']; const sessions=[...mockProgramme,{id:'session-3',time:'14:00',title:'Leadership Roundtable',speaker:'Regional Leaders',venue:'Africa Hall',category:'Leadership'},{id:'session-4',time:'18:30',title:'Nations Worship Night',speaker:'MKAPS Worship Collective',venue:'Main Pavilion',category:'Worship'}]; const shown=filter==='All'?sessions:sessions.filter(s=>s.category===filter); return <Shell eyebrow="Summit schedule" title="Programme"><div className="mt-7 flex gap-2 border-b border-slate-200">{['Today','Upcoming','Full Programme'].map(item=><button key={item} onClick={()=>setTab(item)} className={`border-b-2 px-4 py-3 text-xs font-bold uppercase ${tab===item?'border-mkaps-gold text-mkaps-navy':'border-transparent text-slate-400'}`}>{item}</button>)}</div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{categories.map(item=><button key={item} onClick={()=>setFilter(item)} className={`shrink-0 rounded-full border px-4 py-2 text-xs ${filter===item?'border-mkaps-navy bg-mkaps-navy text-white':'border-slate-200 bg-white'}`}>{item}</button>)}</div><div className="mt-6 space-y-3">{shown.map(session=><article key={session.id} className="grid gap-3 border border-slate-200 bg-white p-5 sm:grid-cols-[90px_1fr_auto] sm:items-center"><strong className="text-mkaps-gold">{session.time}</strong><div><h2 className="font-display text-xl font-semibold">{session.title}</h2><p className="mt-1 text-xs text-slate-500">{session.speaker} · {session.venue}</p></div><span className="text-[.62rem] font-bold uppercase text-slate-500">{session.category} · Scheduled</span></article>)}</div></Shell> }

export function AccommodationPage() { return <Shell eyebrow="Stay information" title="Accommodation"><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_.55fr]"><Panel title="Your Assignment"><Details rows={[["Status","Assigned"],["Type","Summit Camping"],["Facility","MKAPS Summit Camp"],["Check-in","19 Aug 2027 · 14:00"],["Check-out","30 Aug 2027 · 10:00"],["Room / Tent","Tent C-14"],["Location","Summit Grounds, Moshi"],["Contact","+255 700 202 027"]]} /><p className="mt-6 bg-slate-50 p-4 text-sm text-slate-600">Bring a warm sleeping layer. Bedding and a secure storage locker are provided.</p></Panel><Panel title="Need Help?"><p className="text-sm leading-6 text-slate-500">Contact the accommodation desk if your arrival changes or you need accessibility support.</p><button onClick={()=>window.alert('Support request opened locally.')} className="button-navy mt-6 inline-flex">Contact support</button></Panel></div></Shell> }
export function TransportPage() { return <Shell eyebrow="Arrival coordination" title="Transport"><div className="mt-7 grid gap-5 lg:grid-cols-2"><Panel title="Airport Transfer"><Details rows={[["Status","Scheduled"],["Airport","Kilimanjaro International Airport"],["Arrival","19 Aug 2027 · 14:20"],["Pickup point","Terminal 1 Arrivals"],["Shuttle","Kilimanjaro Route A"],["Vehicle","Shuttle K-12"]]} /></Panel><Panel title="Local Shuttle"><Details rows={[["Status","Active"],["Route","Summit Camp ↔ Main Pavilion"],["Frequency","Every 30 minutes"],["Support","+255 700 202 028"]]} /></Panel></div></Shell> }
export function PaymentsPage() { const total=620000, paid=440000; return <Shell eyebrow="Frontend payment record" title="Payments"><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Total Due',total],['Amount Paid',paid],['Balance',total-paid],['Status','Partial']].map(([label,value])=><div key={label} className="border border-slate-200 bg-white p-5"><p className="text-[.62rem] font-bold uppercase text-slate-400">{label}</p><p className="mt-3 text-xl font-bold">{typeof value==='number'?`TZS ${value.toLocaleString()}`:value}</p></div>)}</div><div className="mt-6"><DataTable label="Payment history"><thead><tr>{['Date','Reference','Method','Amount','Status'].map(h=><th key={h} className={tableHeadClass}>{h}</th>)}</tr></thead><tbody>{mockPayments.map(p=><tr key={p.id}><td className={tableCellClass}>{p.date}</td><td className={tableCellClass}>{p.reference}</td><td className={tableCellClass}>{p.method}</td><td className={tableCellClass}>TZS {p.amount.toLocaleString()}</td><td className={tableCellClass}><StatusBadge status={p.status}/></td></tr>)}</tbody></DataTable></div><p className="mt-4 text-xs text-slate-500">Prototype record only. No payment gateway is connected.</p></Shell> }
export function KilimanjaroPage() { return <Shell eyebrow="Mountain activity" title="Kilimanjaro Experience"><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_.65fr]"><Panel title={mockParticipant.kilimanjaroActivity}><Details rows={[["Status","Selected · Screening pending"],["Date","24 Aug 2027"],["Meeting point","Marangu Gate Assembly Area"],["Guide","MKAPS Mountain Team assigned"],["Permit","Pending participant verification"]]} /><p className="mt-6 border-l-4 border-amber-400 bg-amber-50 p-4 text-sm leading-6">Mountain activities may require separate permits, safety screening, guide arrangements and additional fees.</p></Panel><Panel title="What to Bring"><ul className="space-y-3 text-sm text-slate-600">{['Waterproof walking shoes','Warm layered clothing','Two litres of water','Sun protection','Valid identification'].map(item=><li key={item}>— {item}</li>)}</ul></Panel></div></Shell> }
export function AnnouncementsPage() { const [filter,setFilter]=useState('All'); const categories=['All','Important','Programme','Travel','Accommodation','General','Emergency']; const extra=[...mockAnnouncements,{id:'a3',title:'Airport shuttle group assigned',message:'Check your Transport page for pickup details.',category:'Travel' as const,date:'19 Aug 2027 · 09:30'}]; const items=filter==='All'?extra:extra.filter(a=>a.category===filter); return <Shell eyebrow="Event updates" title="Announcements"><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{categories.map(c=><button key={c} onClick={()=>setFilter(c)} className={`shrink-0 rounded-full border px-4 py-2 text-xs ${filter===c?'bg-mkaps-navy text-white':'border-slate-200 bg-white'}`}>{c}</button>)}</div><div className="mt-5 space-y-3">{items.map(item=><article key={item.id} className="border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center gap-3"><span className="text-[.62rem] font-bold uppercase text-mkaps-gold">{item.category}</span><time className="text-xs text-slate-400">{item.date}</time></div><h2 className="mt-3 font-display text-2xl font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{item.message}</p></article>)}</div></Shell> }
export function ProfilePage() { return <Shell eyebrow="Participant account" title="Profile"><div className="mt-7 grid gap-5 lg:grid-cols-2"><Panel title="Personal & Contact"><Details rows={[["Full name",mockParticipant.name],["Country",mockParticipant.country],["Email","neema@example.org"],["Phone","+255 700 000 243"]]} /></Panel><Panel title="Church & Ministry"><Details rows={[["Church","Grace Fellowship Moshi"],["Role","Intercessor"],["Organization","Prayer Network Tanzania"],["Preferences","English · Vegetarian meals"]]} /></Panel><Panel title="Emergency Contact"><Details rows={[["Name","Daniel Mwakalinga"],["Relationship","Brother"],["Phone","+255 700 000 241"]]} /></Panel><Panel title="Travel"><Details rows={[["Arrival airport","Kilimanjaro International"],["Transfer","Requested"],["Accommodation",mockParticipant.accommodation]]} /></Panel></div><button onClick={()=>window.alert('Prototype only: profile edits are not persisted.')} className="button-navy mt-6 inline-flex">Edit profile</button></Shell> }
