import { ArrowLeft, ArrowRight, Check } from 'lucide-react'
import { useState } from 'react'
import { Footer } from '../components/layout/Footer'
import { Header } from '../components/layout/Header'
import { FormSection, SelectInput, TextInput } from '../components/platform/FormControls'
import { registrationService } from '../services/platformServices'
import type { RegistrationDraft } from '../types/operations'

const steps = ['Personal Details', 'Church & Ministry', 'Emergency Contact', 'Accommodation', 'Transport', 'Kilimanjaro', 'Payment', 'Review']
const initialDraft: RegistrationDraft = { fullName: '', gender: '', dateOfBirth: '', nationality: '', countryOfResidence: '', phone: '', email: '', documentType: '', documentNumber: '', churchName: '', denomination: '', churchCity: '', churchCountry: '', ministry: '', churchRole: '', emergencyName: '', emergencyRelationship: '', emergencyPhone: '', emergencyAlternativePhone: '', accommodation: '', budgetPreference: '', roomSharing: '', airportTransfer: 'No', arrivalAirport: '', arrivalDate: '', arrivalTime: '', localShuttle: 'No', ownTransport: 'No', kilimanjaroActivity: '', paymentPreference: '', confirmedAccurate: false }
const accommodations = ['Summit Camping', 'Hotel', 'Lodge', 'Airbnb / Private Accommodation', 'Host Family', 'Self Arranged']
const mountainOptions = ['Summit Programme Only', 'Lower Slopes Prayer Experience', 'Guided Day Hike', 'Multi-Day Kilimanjaro Climb']
const paymentOptions = ['Pay Later', 'Mobile Money', 'Bank Transfer', 'Card Payment']

export function RegistrationPage() {
  const [step, setStep] = useState(0)
  const [draft, setDraft] = useState(initialDraft)
  const [error, setError] = useState('')
  const [confirmation, setConfirmation] = useState<{ registrationNumber: string; participantName: string } | null>(null)
  const update = (field: keyof RegistrationDraft, value: string | boolean) => setDraft((current) => ({ ...current, [field]: value }))
  const validate = () => {
    if (step === 0 && (!draft.fullName || !/^\S+@\S+\.\S+$/.test(draft.email) || draft.phone.replace(/\D/g, '').length < 7)) return 'Enter a full name, valid email address, and valid phone number.'
    if (step === 2 && (!draft.emergencyName || draft.emergencyPhone.replace(/\D/g, '').length < 7)) return 'Provide an emergency contact name and valid phone number.'
    if (step === 3 && !draft.accommodation) return 'Select an accommodation preference.'
    if (step === 5 && !draft.kilimanjaroActivity) return 'Select a Kilimanjaro experience.'
    if (step === 6 && !draft.paymentPreference) return 'Select a payment preference.'
    if (step === 7 && !draft.confirmedAccurate) return 'Confirm that the information is accurate before submitting.'
    return ''
  }
  const next = () => { const message = validate(); setError(message); if (!message) setStep((current) => Math.min(7, current + 1)) }
  const submit = async () => { const message = validate(); setError(message); if (message) return; const result = await registrationService.submit(draft); setConfirmation(result) }

  if (confirmation) return <><Header solid /><main className="min-h-[80vh] bg-mkaps-off-white px-6 pb-20 pt-36 text-mkaps-navy"><div className="mx-auto max-w-2xl border border-mkaps-navy/15 bg-white p-8 text-center shadow-xl sm:p-12"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-100 text-emerald-800"><Check size={30} /></span><p className="eyebrow mt-7">Registration successful</p><h1 className="mt-3 font-display text-5xl font-semibold">Welcome to MKAPS 2027</h1><p className="mt-5 text-slate-500">Your frontend prototype registration has been created locally.</p><div className="mt-8 bg-mkaps-off-white p-5"><p className="text-xs uppercase text-slate-500">Registration number</p><p className="mt-2 text-xl font-bold">{confirmation.registrationNumber}</p><p className="mt-2 text-sm">{confirmation.participantName} · Pending Payment</p></div><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="/portal" className="button-navy inline-flex justify-center">View participant portal</a><button type="button" disabled className="min-h-12 border border-slate-300 px-5 text-xs font-bold uppercase text-slate-400">Download summary · Coming later</button></div></div></main><Footer /></>

  return <><Header solid /><main className="min-h-screen bg-mkaps-off-white pb-20 pt-32 text-mkaps-navy"><div className="mx-auto max-w-6xl px-6 sm:px-8"><p className="eyebrow">MKAPS 2027 registration</p><h1 className="mt-3 font-display text-5xl font-semibold leading-none sm:text-6xl">Begin Your Summit Journey</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-500">Complete the eight steps below. This prototype stores information only in the current page session and does not process payments.</p><ol className="mt-10 flex gap-2 overflow-x-auto pb-3" aria-label="Registration progress">{steps.map((label, index) => <li key={label} className="min-w-32 flex-1"><button type="button" onClick={() => index < step && setStep(index)} className="w-full text-left" disabled={index > step}><span className={`block h-1 ${index <= step ? 'bg-mkaps-gold' : 'bg-slate-200'}`} /><span className="mt-2 block text-[.6rem] font-bold uppercase tracking-wider text-slate-500">{String(index + 1).padStart(2, '0')} · {label}</span></button></li>)}</ol><form onSubmit={(event) => event.preventDefault()} className="mt-8 border border-mkaps-navy/10 bg-white p-6 shadow-[0_16px_45px_rgba(7,26,47,.07)] sm:p-10">
    {step === 0 && <FormSection title="Personal Details"><TextInput label="Full Name" value={draft.fullName} onChange={(e) => update('fullName', e.target.value)} required /><SelectInput label="Gender" value={draft.gender} onChange={(e) => update('gender', e.target.value)}><option value="">Select</option><option>Female</option><option>Male</option><option>Prefer not to say</option></SelectInput><TextInput label="Date of Birth" type="date" value={draft.dateOfBirth} onChange={(e) => update('dateOfBirth', e.target.value)} /><TextInput label="Nationality" value={draft.nationality} onChange={(e) => update('nationality', e.target.value)} /><TextInput label="Country of Residence" value={draft.countryOfResidence} onChange={(e) => update('countryOfResidence', e.target.value)} /><TextInput label="Phone Number" type="tel" value={draft.phone} onChange={(e) => update('phone', e.target.value)} required /><TextInput label="Email Address" type="email" value={draft.email} onChange={(e) => update('email', e.target.value)} required /><SelectInput label="Document Type" value={draft.documentType} onChange={(e) => update('documentType', e.target.value)}><option value="">Select</option><option>Passport</option><option>National ID</option></SelectInput><TextInput label="Document Number" value={draft.documentNumber} onChange={(e) => update('documentNumber', e.target.value)} minLength={5} /></FormSection>}
    {step === 1 && <FormSection title="Church & Ministry"><TextInput label="Church Name" value={draft.churchName} onChange={(e) => update('churchName', e.target.value)} /><TextInput label="Denomination" value={draft.denomination} onChange={(e) => update('denomination', e.target.value)} /><TextInput label="City" value={draft.churchCity} onChange={(e) => update('churchCity', e.target.value)} /><TextInput label="Country" value={draft.churchCountry} onChange={(e) => update('churchCountry', e.target.value)} /><TextInput label="Ministry / Organization" value={draft.ministry} onChange={(e) => update('ministry', e.target.value)} /><SelectInput label="Church Role" value={draft.churchRole} onChange={(e) => update('churchRole', e.target.value)}><option value="">Select</option>{['Apostle','Bishop','Pastor','Evangelist','Prophet','Teacher','Worship Leader','Intercessor','Christian Professional','Business Leader','Youth','Student','Family Participant','Believer','Other'].map((role) => <option key={role}>{role}</option>)}</SelectInput></FormSection>}
    {step === 2 && <FormSection title="Emergency Contact" note="This information is collected for summit safety and emergency coordination."><TextInput label="Contact Name" value={draft.emergencyName} onChange={(e) => update('emergencyName', e.target.value)} required /><TextInput label="Relationship" value={draft.emergencyRelationship} onChange={(e) => update('emergencyRelationship', e.target.value)} /><TextInput label="Phone Number" type="tel" value={draft.emergencyPhone} onChange={(e) => update('emergencyPhone', e.target.value)} required /><TextInput label="Alternative Phone" type="tel" value={draft.emergencyAlternativePhone} onChange={(e) => update('emergencyAlternativePhone', e.target.value)} /></FormSection>}
    {step === 3 && <FormSection title="Accommodation" note="Preferences are for planning only and do not create a booking."><div className="sm:col-span-2 grid gap-3 sm:grid-cols-3">{accommodations.map((option) => <button type="button" key={option} onClick={() => update('accommodation', option)} className={`min-h-24 border p-4 text-left text-sm font-semibold ${draft.accommodation === option ? 'border-mkaps-gold bg-amber-50' : 'border-slate-200'}`}>{option}</button>)}</div><SelectInput label="Budget Preference" value={draft.budgetPreference} onChange={(e) => update('budgetPreference', e.target.value)}><option value="">Select</option><option>Budget</option><option>Standard</option><option>Premium</option></SelectInput><SelectInput label="Room Sharing" value={draft.roomSharing} onChange={(e) => update('roomSharing', e.target.value)}><option value="">Select</option><option>Open to sharing</option><option>Private preferred</option></SelectInput></FormSection>}
    {step === 4 && <FormSection title="Transport"><SelectInput label="Require Airport Transfer?" value={draft.airportTransfer} onChange={(e) => update('airportTransfer', e.target.value)}><option>Yes</option><option>No</option></SelectInput>{draft.airportTransfer === 'Yes' && <><SelectInput label="Arrival Airport" value={draft.arrivalAirport} onChange={(e) => update('arrivalAirport', e.target.value)}><option value="">Select</option><option>Kilimanjaro International Airport</option><option>Arusha Airport</option><option>Other</option></SelectInput><TextInput label="Arrival Date" type="date" value={draft.arrivalDate} onChange={(e) => update('arrivalDate', e.target.value)} /><TextInput label="Arrival Time" type="time" value={draft.arrivalTime} onChange={(e) => update('arrivalTime', e.target.value)} /></>}<SelectInput label="Need Local Shuttle?" value={draft.localShuttle} onChange={(e) => update('localShuttle', e.target.value)}><option>Yes</option><option>No</option></SelectInput><SelectInput label="Own Transport?" value={draft.ownTransport} onChange={(e) => update('ownTransport', e.target.value)}><option>Yes</option><option>No</option></SelectInput></FormSection>}
    {step === 5 && <FormSection title="Kilimanjaro Experience" note="Mountain activities may require separate eligibility, health screening, permits, guide arrangements and additional fees."><div className="sm:col-span-2 grid gap-3 sm:grid-cols-2">{mountainOptions.map((option) => <button type="button" key={option} onClick={() => update('kilimanjaroActivity', option)} className={`min-h-28 border p-5 text-left text-sm font-semibold ${draft.kilimanjaroActivity === option ? 'border-mkaps-gold bg-amber-50' : 'border-slate-200'}`}>{option}</button>)}</div></FormSection>}
    {step === 6 && <FormSection title="Payment Preference" note="Prototype only — payment integration is coming later."><div className="sm:col-span-2 grid gap-3 sm:grid-cols-2">{paymentOptions.map((option) => <button type="button" key={option} onClick={() => update('paymentPreference', option)} className={`border p-5 text-left ${draft.paymentPreference === option ? 'border-mkaps-gold bg-amber-50' : 'border-slate-200'}`}><strong className="text-sm">{option}</strong><span className="mt-1 block text-xs text-slate-500">Payment integration coming later</span></button>)}</div><div className="sm:col-span-2 mt-3 bg-mkaps-off-white p-5 text-sm"><div className="flex justify-between"><span>Registration Fee</span><strong>TZS 250,000</strong></div><div className="mt-3 flex justify-between border-t border-slate-200 pt-3"><span>Total Estimate</span><strong>TZS 250,000 + selected services</strong></div></div></FormSection>}
    {step === 7 && <FormSection title="Review & Submit" note="Review your selections before creating the frontend-only registration."><div className="sm:col-span-2 grid gap-3 sm:grid-cols-2">{[['Participant', draft.fullName || 'Not provided'],['Email', draft.email || 'Not provided'],['Church', draft.churchName || 'Not provided'],['Emergency Contact', draft.emergencyName || 'Not provided'],['Accommodation', draft.accommodation || 'Not selected'],['Transport', draft.airportTransfer === 'Yes' ? 'Airport transfer requested' : 'No airport transfer'],['Kilimanjaro', draft.kilimanjaroActivity || 'Not selected'],['Payment', draft.paymentPreference || 'Not selected']].map(([label,value], index) => <button type="button" key={label} onClick={() => setStep(Math.min(index, 6))} className="border border-slate-200 p-4 text-left"><span className="text-[.6rem] font-bold uppercase text-slate-400">{label} · Edit</span><strong className="mt-1 block text-sm">{value}</strong></button>)}</div><label className="sm:col-span-2 flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1 size-4 accent-mkaps-gold" checked={draft.confirmedAccurate} onChange={(e) => update('confirmedAccurate', e.target.checked)} />I confirm that the information provided is accurate.</label></FormSection>}
    {error && <p role="alert" className="mt-7 border-l-4 border-red-600 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-9 flex items-center justify-between border-t border-slate-200 pt-6"><button type="button" onClick={() => { setError(''); setStep((current) => Math.max(0, current - 1)) }} disabled={step === 0} className="inline-flex min-h-12 items-center gap-2 px-3 text-xs font-bold uppercase disabled:opacity-30"><ArrowLeft size={16} /> Back</button>{step < 7 ? <button type="button" onClick={next} className="button-navy inline-flex">Continue <ArrowRight size={16} /></button> : <button type="button" onClick={submit} className="button-gold inline-flex">Complete registration <Check size={16} /></button>}</div></form></div></main><Footer /></>
}
