import { useState } from 'react'
import { DataTable, tableCellClass, tableHeadClass } from '../../components/platform/DataTable'
import { PageHeader } from '../../components/platform/PageHeader'
import { PrototypeDialog } from '../../components/platform/PrototypeDialog'
import { mockArrivals, mockFacilities, mockRoles } from '../../data/mockPlatform'
import { useMockOperations } from '../../data/mockOperationsContext'
import type { EventSettings, ManagedSpeaker, SpeakerStatus, StaffMember } from '../../types/operations'

const actionClass='text-[.62rem] font-bold uppercase tracking-wider text-mkaps-navy underline decoration-mkaps-gold underline-offset-4'
const inputClass='mt-2 min-h-11 w-full border border-slate-300 bg-white px-3 text-sm font-normal normal-case'
function Shell({title,children}:React.PropsWithChildren<{title:string}>){return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="MKAPS operations" title={title}/><p className="mt-4 border-l-4 border-amber-400 bg-amber-50 p-3 text-xs text-amber-950">Frontend prototype only — actions are not persisted and do not enforce authorization.</p>{children}</div>}

const blankSpeaker: ManagedSpeaker={id:'',fullName:'',title:'',country:'',ministry:'',role:'',category:'',shortBio:'',fullBio:'',session:'',featured:false,status:'Draft',imageReference:'placeholder'}
export function SpeakersAdminPage(){
  const {speakers,saveSpeaker,removeSpeaker,setSpeakerStatus,toggleFeaturedSpeaker}=useMockOperations(); const [editing,setEditing]=useState<ManagedSpeaker|null>(null); const [viewing,setViewing]=useState<ManagedSpeaker|null>(null)
  const update=(key:keyof ManagedSpeaker,value:string|boolean)=>setEditing(current=>current?{...current,[key]:value}:current)
  const submit=()=>{if(!editing||!editing.fullName)return; saveSpeaker({...editing,id:editing.id||`speaker-${Date.now()}`});setEditing(null)}
  return <Shell title="Speakers"><div className="mt-6 flex justify-between"><p className="text-sm text-slate-500">Illustrative records only. Invitation and confirmation states are mock workflow labels.</p><button onClick={()=>setEditing(blankSpeaker)} className="button-navy">Add speaker</button></div><div className="mt-5"><DataTable label="Managed speakers"><thead><tr>{['Speaker','Country','Ministry','Category','Session','Status','Featured','Actions'].map(h=><th key={h} className={tableHeadClass}>{h}</th>)}</tr></thead><tbody>{speakers.map(s=><tr key={s.id}><td className={`${tableCellClass} font-semibold text-slate-900`}>{s.fullName}</td><td className={tableCellClass}>{s.country}</td><td className={tableCellClass}>{s.ministry}</td><td className={tableCellClass}>{s.category}</td><td className={tableCellClass}>{s.session}</td><td className={tableCellClass}><select aria-label={`Status for ${s.fullName}`} value={s.status} onChange={e=>setSpeakerStatus(s.id,e.target.value as SpeakerStatus)} className="border border-slate-200 bg-white p-2">{['Draft','Invited','Pending','Confirmed','Declined','Published'].map(x=><option key={x}>{x}</option>)}</select></td><td className={tableCellClass}><button className={actionClass} onClick={()=>toggleFeaturedSpeaker(s.id)}>{s.featured?'Unfeature':'Feature'}</button></td><td className={tableCellClass}><div className="flex gap-3"><button className={actionClass} onClick={()=>setViewing(s)}>View</button><button className={actionClass} onClick={()=>setEditing(s)}>Edit</button><button className={actionClass} onClick={()=>removeSpeaker(s.id)}>Remove</button></div></td></tr>)}</tbody></DataTable></div>
  <PrototypeDialog open={Boolean(editing)} title={editing?.id?'Edit Speaker':'Add Speaker'} onClose={()=>setEditing(null)}>{editing&&<div className="grid gap-4 sm:grid-cols-2">{([['fullName','Full Name'],['title','Title'],['country','Country'],['ministry','Ministry / Organization'],['role','Role'],['category','Category'],['session','Session'],['imageReference','Image reference / placeholder']] as const).map(([key,label])=><label key={key} className="text-xs font-bold uppercase">{label}<input value={String(editing[key])} onChange={e=>update(key,e.target.value)} className={inputClass}/></label>)}<label className="sm:col-span-2 text-xs font-bold uppercase">Short Bio<textarea value={editing.shortBio} onChange={e=>update('shortBio',e.target.value)} className={`${inputClass} min-h-20 p-3`}/></label><label className="sm:col-span-2 text-xs font-bold uppercase">Full Bio<textarea value={editing.fullBio} onChange={e=>update('fullBio',e.target.value)} className={`${inputClass} min-h-24 p-3`}/></label><label className="flex items-center gap-2 text-sm normal-case"><input type="checkbox" checked={editing.featured} onChange={e=>update('featured',e.target.checked)}/>Featured</label><label className="text-xs font-bold uppercase">Status<select value={editing.status} onChange={e=>update('status',e.target.value)} className={inputClass}>{['Draft','Invited','Pending','Confirmed','Declined','Published'].map(x=><option key={x}>{x}</option>)}</select></label><button onClick={submit} className="button-gold sm:col-span-2">Save prototype speaker</button></div>}</PrototypeDialog>
  <PrototypeDialog open={Boolean(viewing)} title="Speaker Profile" onClose={()=>setViewing(null)}>{viewing&&<div><p className="text-xs font-bold uppercase text-mkaps-gold">{viewing.country} · {viewing.status}</p><h3 className="mt-3 font-display text-3xl font-semibold">{viewing.fullName}</h3><p className="mt-2 text-sm text-slate-500">{viewing.role}, {viewing.ministry}</p><p className="mt-5 text-sm leading-7">{viewing.fullBio}</p><p className="mt-5 bg-amber-50 p-3 text-xs">Illustrative sample — not a confirmed MKAPS 2027 participant.</p></div>}</PrototypeDialog></Shell>
}

function ReportCard({label,value,detail,progress}:{label:string;value:string;detail:string;progress?:number}){return <article className="border border-slate-200 bg-white p-5"><p className="text-[.62rem] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold text-mkaps-navy">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p>{progress!==undefined&&<div className="mt-4 h-2 bg-slate-100"><div className="h-full bg-mkaps-gold" style={{width:`${Math.min(100,progress)}%`}}/></div>}</article>}
export function ReportsAdminPage(){const {registrations}=useMockOperations(); const [year,setYear]=useState('2027');const [country,setCountry]=useState('All');const [status,setStatus]=useState('All');const filtered=registrations.filter(r=>(country==='All'||r.country===country)&&(status==='All'||r.registrationStatus===status));const total=filtered.length,confirmed=filtered.filter(r=>r.registrationStatus==='confirmed').length,expected=filtered.reduce((n,r)=>n+r.expectedAmount,0),paid=filtered.reduce((n,r)=>n+r.paidAmount,0),checked=filtered.filter(r=>r.checkedIn).length,assigned=filtered.filter(r=>!r.accommodation.toLowerCase().includes('requested')).length,transfers=filtered.filter(r=>r.transport.toLowerCase().includes('transfer')).length;const exportCsv=()=>{const csv=['Registration,Participant,Country,Status,Payment',...filtered.map(r=>[r.registrationNumber,r.name,r.country,r.registrationStatus,r.paymentStatus].join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='mkaps-2027-report.csv';link.click();URL.revokeObjectURL(url)};return <Shell title="Reports"><div className="mt-6 grid gap-3 sm:grid-cols-4"><select aria-label="Event year" value={year} onChange={e=>setYear(e.target.value)} className={inputClass}><option>2027</option></select><select aria-label="Country" value={country} onChange={e=>setCountry(e.target.value)} className={inputClass}><option>All</option>{[...new Set(registrations.map(r=>r.country))].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Registration status" value={status} onChange={e=>setStatus(e.target.value)} className={inputClass}><option>All</option><option value="confirmed">Confirmed</option><option value="pending_payment">Pending payment</option><option value="submitted">Submitted</option></select><button onClick={exportCsv} className="button-navy self-end">Export report</button></div><div className="mt-7 space-y-7">{[
  ['Registration',[['Total registrations',String(total),`${year} filtered records`],['Confirmed',String(confirmed),'Confirmed participants',total?confirmed/total*100:0],['Pending',String(total-confirmed),'Awaiting completion'],['Cancelled','0','No mock cancellations'],['Countries',String(new Set(filtered.map(r=>r.country)).size),'Represented']]],
  ['Payments',[['Expected',`TZS ${expected.toLocaleString()}`,'Mock total'],['Amount paid',`TZS ${paid.toLocaleString()}`,'Recorded payments',expected?paid/expected*100:0],['Outstanding',`TZS ${(expected-paid).toLocaleString()}`,'Balance'],['Completion',`${expected?Math.round(paid/expected*100):0}%`,'Payment completion',expected?paid/expected*100:0]]],
  ['Accommodation',[['Requests',String(total),'Participant requests'],['Assigned',String(assigned),'Facility assigned',total?assigned/total*100:0],['Unassigned',String(total-assigned),'Requires assignment'],['Capacity used',`${Math.round(mockFacilities.reduce((n,f)=>n+f.occupied,0)/mockFacilities.reduce((n,f)=>n+f.capacity,0)*100)}%`,'Across mock facilities']]],
  ['Transport',[['Transfers requested',String(transfers),'Airport transfers'],['Assigned',String(mockArrivals.filter(a=>a.vehicle!=='Unassigned').length),'Vehicle assigned'],['Unassigned',String(mockArrivals.filter(a=>a.vehicle==='Unassigned').length),'Needs assignment'],['Arrivals by airport',String(new Set(mockArrivals.map(a=>a.airport)).size),'Airports represented']]],
  ['Kilimanjaro',[['Programme only',String(filtered.filter(r=>r.kilimanjaroActivity.includes('Programme')).length),'Participants'],['Lower slopes',String(filtered.filter(r=>r.kilimanjaroActivity.includes('Lower')).length),'Participants'],['Guided day hike',String(filtered.filter(r=>r.kilimanjaroActivity.includes('Guided')).length),'Participants'],['Multi-day climb',String(filtered.filter(r=>r.kilimanjaroActivity.includes('Multi')).length),'Participants']]],
  ['Check-In',[['Checked in',String(checked),'Participants',total?checked/total*100:0],['Not checked in',String(total-checked),'Participants'],['Check-in rate',`${total?Math.round(checked/total*100):0}%`,'Completion',total?checked/total*100:0]]]
].map(([section,cards])=><section key={section as string}><h2 className="text-sm font-bold uppercase tracking-wider">{section as string}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(cards as Array<[string,string,string,number?]>).map(([label,value,detail,progress])=><ReportCard key={label} label={label} value={value} detail={detail} progress={progress}/>)}</div></section>)}</div></Shell>}

const blankStaff:StaffMember={id:'',name:'',email:'',role:'Registration Officer',department:'Registration',status:'Active',lastActive:'Never'}
export function StaffAdminPage(){const {staff,saveStaff,toggleStaffStatus}=useMockOperations();const [tab,setTab]=useState('Staff Members');const [editing,setEditing]=useState<StaffMember|null>(null);const update=(key:keyof StaffMember,value:string)=>setEditing(c=>c?{...c,[key]:value}:c);return <Shell title="Staff & Roles"><div className="mt-6 flex gap-2 border-b border-slate-200">{['Staff Members','Roles & Permissions'].map(t=><button key={t} onClick={()=>setTab(t)} className={`border-b-2 px-4 py-3 text-xs font-bold ${tab===t?'border-mkaps-gold':'border-transparent'}`}>{t}</button>)}</div>{tab==='Staff Members'?<><div className="mt-5 text-right"><button onClick={()=>setEditing(blankStaff)} className="button-navy">Add staff</button></div><div className="mt-4"><DataTable label="Staff members"><thead><tr>{['Name','Email','Role','Department','Status','Last Active','Actions'].map(h=><th key={h} className={tableHeadClass}>{h}</th>)}</tr></thead><tbody>{staff.map(s=><tr key={s.id}><td className={`${tableCellClass} font-semibold`}>{s.name}</td><td className={tableCellClass}>{s.email}</td><td className={tableCellClass}>{s.role}</td><td className={tableCellClass}>{s.department}</td><td className={tableCellClass}>{s.status}</td><td className={tableCellClass}>{s.lastActive}</td><td className={tableCellClass}><div className="flex gap-3"><button className={actionClass} onClick={()=>setEditing(s)}>Edit / Role</button><button className={actionClass} onClick={()=>toggleStaffStatus(s.id)}>{s.status==='Active'?'Deactivate':'Activate'}</button></div></td></tr>)}</tbody></DataTable></div></>:<><p className="mt-5 bg-amber-50 p-4 text-xs text-amber-950">Frontend prototype only — these controls do not enforce real authorization. Production authorization must be enforced server-side.</p><div className="mt-4"><DataTable label="Role permission matrix"><thead><tr><th className={tableHeadClass}>Role</th>{Object.keys(mockRoles[0].permissions).map(a=><th key={a} className={tableHeadClass}>{a}</th>)}</tr></thead><tbody>{mockRoles.map(r=><tr key={r.name}><td className={`${tableCellClass} sticky left-0 bg-white font-semibold`}>{r.name}</td>{Object.values(r.permissions).map((level,i)=><td key={i} className={tableCellClass}><span className="font-bold">{level}</span></td>)}</tr>)}</tbody></DataTable></div></>}
<PrototypeDialog open={Boolean(editing)} title={editing?.id?'Edit Staff Member':'Add Staff Member'} onClose={()=>setEditing(null)}>{editing&&<div className="grid gap-4">{([['name','Name'],['email','Email'],['department','Department']] as const).map(([key,label])=><label key={key} className="text-xs font-bold uppercase">{label}<input value={editing[key]} onChange={e=>update(key,e.target.value)} className={inputClass}/></label>)}<label className="text-xs font-bold uppercase">Role<select value={editing.role} onChange={e=>update('role',e.target.value)} className={inputClass}>{mockRoles.map(r=><option key={r.name}>{r.name}</option>)}</select></label><button onClick={()=>{saveStaff({...editing,id:editing.id||`staff-${Date.now()}`});setEditing(null)}} className="button-gold">Save mock staff</button></div>}</PrototypeDialog></Shell>}

export function SettingsAdminPage(){const {settings,updateSettings}=useMockOperations();const [draft,setDraft]=useState(settings);const [tab,setTab]=useState('Event');const update=(key:keyof EventSettings,value:string|number|boolean)=>setDraft(c=>({...c,[key]:value}));const text=(key:keyof EventSettings,label:string,type='text')=><label className="text-xs font-bold uppercase">{label}<input type={type} value={String(draft[key])} onChange={e=>update(key,type==='number'?Number(e.target.value):e.target.value)} className={inputClass}/></label>;const toggle=(key:keyof EventSettings,label:string,note?:string)=><label className="flex items-start justify-between gap-4 border border-slate-200 bg-white p-4 text-sm"><span><strong className="block">{label}</strong>{note&&<span className="mt-1 block text-xs text-slate-400">{note}</span>}</span><input type="checkbox" checked={Boolean(draft[key])} onChange={e=>update(key,e.target.checked)} className="size-5 accent-mkaps-gold"/></label>;return <Shell title="Settings"><div className="mt-6 flex gap-1 overflow-x-auto border-b border-slate-200">{['Event','Registration','Branding','Communication','Operations','Prototype / Developer'].map(t=><button key={t} onClick={()=>setTab(t)} className={`shrink-0 border-b-2 px-4 py-3 text-xs font-bold ${tab===t?'border-mkaps-gold':'border-transparent'}`}>{t}</button>)}</div><section className="mt-5 border border-slate-200 bg-white p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2">
{tab==='Event'&&<>{text('eventName','Event Name')}{text('theme','Theme')}{text('startDate','Start Date','date')}{text('endDate','End Date','date')}{text('venue','Venue')}{text('city','City')}{text('country','Country')}{text('attendanceTarget','Attendance Target','number')}</>}
{tab==='Registration'&&<>{toggle('registrationOpen','Registration Open')}{text('registrationDeadline','Registration Deadline','date')}{text('registrationCapacity','Registration Capacity','number')}{toggle('allowWaitlist','Allow Waitlist')}{toggle('requirePayment','Require Payment Before Confirmation')}{toggle('allowKilimanjaro','Allow Kilimanjaro Activities')}</>}
{tab==='Branding'&&<><div className="sm:col-span-2 flex items-center gap-5 bg-mkaps-navy p-5 text-white"><div className="grid size-16 place-items-center border border-mkaps-gold font-display text-2xl">MK</div><div><strong>MKAPS logo preview</strong><p className="text-xs text-white/50">Uploads are not enabled.</p></div></div>{text('primaryColor','Primary Color','color')}{text('secondaryColor','Secondary Color','color')}<label className="sm:col-span-2 text-xs font-bold uppercase">Theme Text<input value={draft.themeText} onChange={e=>update('themeText',e.target.value)} className={inputClass}/></label></>}
{tab==='Communication'&&<>{toggle('emailConfirmations','Email Confirmations','Not connected — future backend integration')}{toggle('smsUpdates','SMS Updates','Not connected — future backend integration')}{toggle('whatsappUpdates','WhatsApp Updates','Not connected — future backend integration')}{toggle('pushNotifications','Push Notifications','Not connected — future backend integration')}</>}
{tab==='Operations'&&<>{toggle('qrCheckIn','QR Check-In Enabled')}{toggle('manualCheckIn','Manual Check-In Allowed')}{toggle('accommodationAllocation','Accommodation Allocation Enabled')}{toggle('airportTransfers','Airport Transfer Coordination Enabled')}{toggle('emergencyMode','Emergency Announcement Mode')}</>}
{tab==='Prototype / Developer'&&<><div className="sm:col-span-2 bg-amber-50 p-5 text-sm leading-7 text-amber-950"><strong>Prototype environment</strong><ul className="mt-2"><li>Mock data enabled: Yes</li><li>Frontend-only mode: Yes</li><li>Dev role switcher enabled: Yes</li></ul><p className="mt-3 font-semibold">These controls are not production security and do not enforce authorization.</p></div></>}
</div><button onClick={()=>updateSettings(draft)} className="button-gold mt-7">Save prototype settings</button></section></Shell>}
