import { useOutletContext } from 'react-router-dom'
import { DashboardCard } from '../../components/platform/DashboardCard'
import { PageHeader } from '../../components/platform/PageHeader'
import { adminMetrics, mockAnnouncements } from '../../data/mockPlatform'
import type { DevRole } from '../../types/operations'

export function AdminDashboardPage() {
  const { role } = useOutletContext<{ role: DevRole }>()
  return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="Operations overview" title="Admin Dashboard"><p className="text-xs text-slate-500">Viewing mock permissions as <strong className="text-slate-900">{role}</strong></p></PageHeader><div className="mt-5 border-l-4 border-amber-400 bg-amber-50 p-4 text-xs leading-5 text-amber-950"><strong>DEV PROTOTYPE:</strong> Metrics and actions are mock frontend data. No administrative authorization or backend writes are active.</div><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Event metrics">{adminMetrics.map((metric) => <DashboardCard key={metric.label} {...metric} />)}</section><div className="mt-8 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><section className="overflow-hidden border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Registration activity</h2><p className="mt-1 text-xs text-slate-500">Seven-day mock trend</p></div><div className="flex h-52 items-end gap-3 p-6" aria-label="Mock registration bar chart">{[42,58,48,76,64,88,72].map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full bg-mkaps-navy" style={{ height: `${height}%` }} /><span className="text-[.6rem] text-slate-400">D{index + 1}</span></div>)}</div></section><section className="border border-slate-200 bg-white p-5"><h2 className="font-semibold">Operational notices</h2><div className="mt-4 space-y-5">{mockAnnouncements.map((item) => <article key={item.id}><p className="text-[.6rem] font-bold uppercase text-mkaps-gold">{item.category}</p><h3 className="mt-1 text-sm font-semibold">{item.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{item.message}</p></article>)}</div></section></div></div>
}
